### ISSUE TITLE
 common

### ISSUE THREAD

**Issue by hayashi-trym** [trymcom/html#5]
## mixin,functionについて
以下の他に、何か良いものありますか？

- サイズの%指定
- 画面サイズがinner以下になったらフォントをvwにする
- letter-spacing
- line-height

また、現在の_vars.scssで使用していない、今後使わないと思うmixinやfunctionはありますか？

## 対応ブラウザの確認
すみません、今まで\<picture\>など乱用してしまったので、
初めて使用する要素やスタイルについては、[can i use](https://caniuse.com/)で使用可能バージョンを確認するなどのルールを加えた方が良いと思いますが、どうしますか？

案件にも寄ると思うのですが、基本は「IE11,firefox最新、chrome最新、社内のテスト端末のver」でしょうか？

## \<main\>について
全く再現できないのですが、Windows10のIEで\<main\>を認識せず、表示されないことがあるそうです。
\<div class="main" role="main"\>のようにした方が良いのでしょうか？

**Comment by leo-trym** [comment]
ありがとうございます。  
時間のある時にみんなで整理したいですね。

パーセント指定については先日下記のような物を作りました。

```scss
@function widtnPercent( $parentPxWidth, $pxWidth ){
  @return floor((( $pxWidth / $parentPxWidth ) * 10000% )) / 100;
}
```
widtnPercent(親のpx, 指定したいpx)

#### 例

```css
.elem {
  width: widtnPercent(1280, 1200);
  padding: 0 widtnPercent(1280, 40);
  margin-bottom: widtnPercent(670, 40);
}
```

またCSSファイルの管理についても、  
今までのように common.scss にすべて書く方法だと長くなってしまうため、  
今回の案件から要素ごとに分割してみました。

https://github.com/trymcom/sanyo-mag/tree/master/common/css

こうするとメディアクエリをネストしても、  
ある程度分かりやすい気がしています。
